version: '3.8'

services:

  kraken-app:
      build:
        context: ./src/kraken
        dockerfile: Dockerfile.kraken
      ports:
        - "1935:1935"
      environment:
        - DISPLAY=${DISPLAY}
      volumes: #Mounting these volumes allows us to avoid building kfr inside the container
               #Docker does not support wildcard matching and we do not want to mount the whole /usr/local/lib dir
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /usr/local/lib/libkfr_capi_avx2.a:/usr/local/lib/libkfr_capi_avx2.a
        - /usr/local/lib/libkfr_capi_avx2_pic.a:/usr/local/lib/libkfr_capi_avx2_pic.a
        - /usr/local/lib/libkfr_capi_avx512.a:/usr/local/lib/libkfr_capi_avx512.a
        - /usr/local/lib/libkfr_capi_avx512_pic.a:/usr/local/lib/libkfr_capi_avx512_pic.a
        - /usr/local/lib/libkfr_capi_avx.a:/usr/local/lib/libkfr_capi_avx.a
        - /usr/local/lib/libkfr_capi.so:/usr/local/lib/libkfr_capi.so
        - /usr/local/lib/libkfr_capi_avx_pic.a:/usr/local/lib/libkfr_capi_avx_pic.a
        - /usr/local/lib/libkfr_capi_sse2.a:/usr/local/lib/libkfr_capi_sse2.a
        - /usr/local/lib/libkfr_capi_sse2_pic.a:/usr/local/lib/libkfr_capi_sse2_pic.a
        - /usr/local/lib/libkfr_capi_sse41.a:/usr/local/lib/libkfr_capi_sse41.a
        - /usr/local/lib/libkfr_capi_sse41_pic.a:/usr/local/lib/libkfr_capi_sse41_pic.a
        - /usr/include/kfr/capi.h:/usr/include/kfr/capi.h
      privileged: true
      
  pluto-app:
      build:
        context: ./src/plutosdr
        dockerfile: Dockerfile.pluto
      ports:
        - "1935:1935"
      environment:
        - QT_QPA_PLATFORM=xcb
        - DISPLAY=${DISPLAY}
        - QT_DEBUG_PLUGINS=1
      volumes: 
        - /tmp/.X11-unix:/tmp/.X11-unix
        # - ./data:/app/data
        # - ./:/app
      env_file:
        - ./src/plutosdr/.env
      privileged: true