#Use an official Python runtime as a parent image
FROM continuumio/miniconda3

#Use mamba instead for faster environment creation
RUN conda install -c conda-forge mamba

#Install necessary packages
RUN apt-get update && apt-get install -y \
    lsof \
    libgl1-mesa-glx \
    nano \
    libzmq3-dev \
    libusb-1.0-0 \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-tools \
    gstreamer1.0-x \
    gstreamer1.0-alsa \ 
    gstreamer1.0-gl \
    gstreamer1.0-gtk3 \ 
    gstreamer1.0-qt5 \
    gstreamer1.0-pulseaudio && \
    rm -rf /var/lib/apt/lists/*

#Set the working directory in the container
WORKDIR /src/kraken

#Copy the requirements file into the container
COPY environment.yml .

#Install any dependencies
RUN conda env create -f environment.yml

#Copy the start.sh script and make it executable
COPY start_doa.sh .
RUN chmod +x start_doa.sh

#Copy the rest of the application code into the container
COPY . .

ENTRYPOINT ["./start_doa.sh"]