name: pluto
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy 
  - scipy
  - scikit-rf=1.1.0
  - conda-forge::pyadi-iio
  - qt 
  - pyqt 
  - pyqtgraph
  - glib
  - conda-forge::pygobject 
  - pyzmq
  - cairo
  - pycairo
  - opencv 
  - gstreamer
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - gst-libav
  - gst-plugins-base            
  - x264
  - libxcb
  - pylibiio
